import Link from 'next/link'
import { TrendingUp } from 'lucide-react'
import AdPlaceholder from '@/components/AdPlaceholder'
import Disclaimer from '@/components/Disclaimer'

const NAV_LINKS = ['Home', 'Stock Insights', 'My Watchlist', 'About Us']
const LEGAL_LINKS = [
  { label: 'Privacy Policy',   href: '/legal#privacy'   },
  { label: 'Terms of Service', href: '/legal#terms'     },
  { label: 'Cookie Policy',    href: '/legal#cookies'   },
  { label: 'Full Disclaimer',  href: '/legal#disclaimer'},
  { label: 'GDPR Notice',      href: '/legal#gdpr'      },
  { label: 'FINSA / EU Notice',href: '/legal#finsa'     },
]
const RESOURCE_LINKS = [
  { label: 'AI Agent Instructions', href: '/ai-agent-instructions' },
  { label: 'Stock Upload Admin',    href: '/admin'                 },
  { label: 'RSS Feed',              href: '/feed.xml'              },
  { label: 'Sitemap',               href: '/sitemap.xml'           },
]

export default function Footer() {
  const year = new Date().getFullYear()

  return (
    <>
      {/* Full-width disclaimer bar above footer */}
      <Disclaimer variant="bar" />

      <footer className="bg-gray-950 border-t border-gray-800 pt-10 pb-6 px-4">
        <div className="max-w-7xl mx-auto">

          {/* ── Main grid ── */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-8">

            {/* Brand column */}
            <div className="col-span-2 md:col-span-1">
              <div className="flex items-center gap-2 mb-3">
                <div className="w-7 h-7 bg-blue-700 rounded-lg flex items-center justify-center">
                  <TrendingUp size={14} className="text-white" />
                </div>
                <span className="font-black text-white text-sm">Alpha Stocks Insight</span>
              </div>
              <p className="text-gray-500 text-xs leading-relaxed mb-4">
                Independent AI-powered stock news and investment ideas for US market investors.
                Not affiliated with any broker, fund, or financial institution.
              </p>
              {/* AD PLACEHOLDER (footer) — replace with real AdSense unit */}
              <AdPlaceholder size="320x50" label="Footer Banner (320×50)" />
            </div>

            {/* Navigation */}
            <div>
              <h4 className="text-white font-bold text-sm mb-3">Navigation</h4>
              <ul className="space-y-2">
                {NAV_LINKS.map((l) => (
                  <li key={l}>
                    <Link
                      href={`/${l.toLowerCase().replace(/\s+/g, '-').replace('home', '')}`}
                      className="text-gray-500 text-xs hover:text-gray-300 transition-colors"
                    >
                      {l}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Legal */}
            <div>
              <h4 className="text-white font-bold text-sm mb-3">Legal</h4>
              <ul className="space-y-2">
                {LEGAL_LINKS.map((l) => (
                  <li key={l.href}>
                    <Link href={l.href} className="text-gray-500 text-xs hover:text-gray-300 transition-colors">
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>

            {/* Resources */}
            <div>
              <h4 className="text-white font-bold text-sm mb-3">Resources</h4>
              <ul className="space-y-2">
                {RESOURCE_LINKS.map((l) => (
                  <li key={l.href}>
                    <Link href={l.href} className="text-gray-500 text-xs hover:text-gray-300 transition-colors">
                      {l.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* ── Bottom bar ── */}
          <div className="border-t border-gray-800 pt-5 flex flex-col sm:flex-row items-center justify-between gap-3">
            <p className="text-gray-600 text-xs">
              © {year} Alpha Stocks Insight. All rights reserved.
            </p>
            <p className="text-gray-700 text-xs text-center sm:text-right">
              Content generated by AI for informational purposes only · Not financial advice ·
              Investing involves risk of loss
            </p>
          </div>

        </div>
      </footer>
    </>
  )
}
